// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RequestApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528033429_AddRequiresCustomTemplate")]
    partial class AddRequiresCustomTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomTemplate")
                        .HasColumnType("text")
                        .HasColumnName("custom_template");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_requests_status_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_requests_type_id");

                    b.HasIndex("EmployeeId", "TypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_requests_employee_id_type_id")
                        .HasFilter("is_active = true");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_request_statuses");

                    b.ToTable("request_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsTerminal = false,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            IsTerminal = false,
                            Name = "InReview"
                        },
                        new
                        {
                            Id = 3,
                            IsTerminal = true,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 4,
                            IsTerminal = true,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("RequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("from_status_id");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("to_status_id");

                    b.HasKey("Id")
                        .HasName("pk_request_status_histories");

                    b.HasIndex("FromStatusId")
                        .HasDatabaseName("ix_request_status_histories_from_status_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_request_status_histories_request_id");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_request_status_histories_to_status_id");

                    b.ToTable("request_status_histories", (string)null);
                });

            modelBuilder.Entity("RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresCustomTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_custom_template");

                    b.HasKey("Id")
                        .HasName("pk_request_types");

                    b.ToTable("request_types", (string)null);
                });

            modelBuilder.Entity("Request", b =>
                {
                    b.HasOne("RequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requests_request_statuses_status_id");

                    b.HasOne("RequestType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requests_request_types_type_id");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("RequestStatusHistory", b =>
                {
                    b.HasOne("RequestStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .HasConstraintName("fk_request_status_histories_request_statuses_from_status_id");

                    b.HasOne("Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_status_histories_requests_request_id");

                    b.HasOne("RequestStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_status_histories_request_statuses_to_status_id");

                    b.Navigation("FromStatus");

                    b.Navigation("Request");

                    b.Navigation("ToStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
